### PR TITLE
switch to orm model

### PR DESCRIPTION
**Pull request by mitchdennett**
Update to use new Masonite ORM instead of Orator

Requires this PR - https://github.com/MasoniteFramework/orm/pull/484 - since we use Pendulum for dates.

### CODE REVIEW

**Review by girardinsamuel — CHANGES_REQUESTED** [review]
Looks good !
It would be nice to update the `config/database.py` file of this repo.
You can replace it with this one 
https://github.com/MasoniteFramework/masonite/blob/3.0/config/database.py

**Review by josephmancuso — APPROVED** [review]
Theres no code changes required? wow I'm impressed lol. Masonite ORM is a pretty damn good drop in replacement for Orator I guess

**Comment by josephmancuso** [comment]
I think there are more changes required here. I might have a copy of the changes somewhere local I'll need to check it

**Comment by josephmancuso** [comment]
masonitecasts.com is running Masonite 3 right now and Masonite billing 3.0.1 but I don't see the changes in this repo

**Comment by mitchdennett** [comment]
> masonitecasts.com is running Masonite 3 right now and Masonite billing 3.0.1 but I don't see the changes in this repo

Yeah the repo currently would not work. There are imports from orator still. Was there a release but the changes didn't get pushed?

**Comment by mitchdennett** [comment]
The last tag on this repo is 0.1.4. The pypi has a lot more releases.

**Comment by mitchdennett** [comment]
Wait, I guess my changes aren't actually needed then. Since we import Models from config.py. Ill just make sure my database config has models and then it should just work. I'm assuming the config in this repo isn't actually the one used. It'll use the application config

**Comment by girardinsamuel** [comment]
This package has been updated for Masonite4 which is using Masonite ORM, so I will close this PR.

**Pull request closed without merging**
